### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'mime' (line 35)

### ISSUE THREAD

**Issue by anthaeus** [secrary/SSMA#1]
line 35: filetype=Magic(mime=True).from_file(args.filename)

Regards

**Comment by secrary** [comment]
What OS do you currently use?
Can you post some screenshots and/or snippets?
Thanks...

**Comment by anthaeus** [comment]
blackarch

**Comment by secrary** [comment]
I think this problem is something about different implementations of "python-magic".
This code works (tested by me) on ArchLinux, Ubuntu 14.04 and Ubuntu 16.04.

**Comment by secrary** [comment]
uninstall filemagic:
`sudo pip3 uninstall filemagic`
uninstall python-magic:
`sudo pip3 uninstall python-magic`
install python-magic:
`sudo pip3 install python-magic`

**Comment by anthaeus** [comment]
Yes, that was the case, thank you for your reply.
