### ISSUE TITLE
Report to JSON

### ISSUE THREAD

**Issue by pielco11** [secrary/SSMA#12]
Tried `report to JSON`, why report is shorter than the actual output?

**Comment by secrary** [comment]
@firmianay writes this part, Some functions in the report function are commented. You can check it

**Comment by firmianay** [comment]
I am sorry that this part of the code has not yet finished, and "check_file.py" may need to refactor to make a better report.
And I am reviewing the final exam, so it may take some time to update. Maybe you can help finish it. Thx

**Comment by pielco11** [comment]
No problem, it was just to understand. I'll contribute because I'm interested too in this feature.

**Comment by pielco11** [comment]
I thought that the `report to JSON` part was complete, but I see some strange `\u0000\u0000\u0000` and (for example) `"date": "\u001b[1;31m [SUSPICIOUS COMPILATION DATE] - 1970\u001b[0;0m"`. I can't figure out why. How is possible to solve this? 

(Nonetheless, I'll delete my "way" to print out JSON and substitute it with the right way)

**Comment by secrary** [comment]
check now

**Comment by firmianay** [comment]
It confused me too, thanks to @secrary.
I fixed another bugs, check now

**Comment by pielco11** [comment]
After the merge, everything should work as expected
