### ISSUE TITLE
pe import in packer.yar

### ISSUE THREAD

**Issue by tehfcae** [secrary/SSMA#3]
Whenever I try to SSMA, most of it goes without issue, however, once it gets to the yara rules it fails. Regardless of if I try to re-download yara rules or not I get the error undefined identifier "pe" in rules/Packers/packer.yar.

I tried changing it be pefile, which I have installed, but it still fails with the same issue. Any suggestions?

**Comment by secrary** [comment]
Can you check Yara version? 
`yara --version   `

Your Yara has to support PE module.

**Comment by tehfcae** [comment]
I have tried with Yara 3.4 and Yara 3.5

I went through and set pe to point to pefile, and I am still getting the error.

If it helps I also tried to manually run some of the attributes ( example: pe.entry_point) in python and got the error: module 'pe' has no attribute 'entry_point'

**Comment by secrary** [comment]
What OS are you using?
Can you provide a screenshot of the error?

**Comment by tehfcae** [comment]
Ubuntu 16.04

![screen shot 2017-03-01 at 4 22 21 pm](https://cloud.githubusercontent.com/assets/15707372/23487512/746799d0-fe9b-11e6-9b39-d7f1da92bbb6.png)

**Comment by tehfcae** [comment]
I ended up rebuilding this VM due to a space issue and and new VM is working without any problems
