### ISSUE TITLE
Update and report flag is throwing back errors

### ISSUE THREAD

**Issue by Evan-Sa** [secrary/SSMA#36]
update feature does not work see command output below. Correct me if I am wrong but new yara rules are downloaded if they exist from the main repo everytime ssma is run or are they not updating at all 

remnux@siftworkstation:~/Desktop/SSMA$ ./ssma.py -u 
usage: ssma.py [-h] [-k API_KEY] [-d] [-u UPDATE] [-y YARA] [-D DIRECTORY]
               [-r REPORT] [-t]
               filename
ssma.py: error: argument -u/--update: expected one argument

~/Desktop/SSMA$ ./ssma.py -u mal.exe 
usage: ssma.py [-h] [-k API_KEY] [-d] [-u UPDATE] [-y YARA] [-D DIRECTORY]
               [-r REPORT] [-t]
               filename
ssma.py: error: the following arguments are required: filename
remnux@siftworkstation:~/Desktop/SSMA$

Similar issue with the report feature as well

remnux@siftworkstation:~/Desktop/SSMA$ ssma -r  '/home/remnux/malware-samples/Macro-Ransomeware/bleachbit-test'
usage: ssma.py [-h] [-k API_KEY] [-d] [-F FLUSH] [-u UPDATE] [-y YARA]
               [-D DIRECTORY] [-r REPORT] [-t]
               filename
ssma.py: error: the following arguments are required: filename

**Comment by secrary** [comment]
for update yara rules you need this: ./ssma.py sample.exe -u yes

where sample.exe is some executable which you what to check, you can't update rules separately

**Comment by Evan-Sa** [comment]
you're right  I misunderstood the instructions this is a not issue then.
thank you for the clarification
