### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by aflexa** [secrary/SSMA#4]
Hi, can you provide test samples since the tool is not working for a real malicious samples

Thank you

**Comment by secrary** [comment]
what errors are you getting?

**Comment by aflexa** [comment]
Number of Sections: 6

Section VirtualAddress VirtualSize SizeofRawData Entropy
Traceback (most recent call last):
  File "ssma.py", line 55, in <module>
    pe.sections_analysis()
  File "/home/remnux/Desktop/SSMA/src/check_file.py", line 241, in sections_analysis
    sec_name = section.Name.strip(b"\x00").decode(errors='ignore')
TypeError: strip arg must be None or str

**Comment by secrary** [comment]
Please check this now, I've changed some statements.

**Comment by aflexa** [comment]
Still getting the error...

**Comment by secrary** [comment]
Can you post the sample?

**Comment by aflexa** [comment]
The sample can be found at the following repo:
https://github.com/JonathanSalwan/binary-samples

Tested sample: pe-Windows-x64-cmd

However it is not the only sample that does not work. Pretty much all win samples throw the same error.

**Comment by secrary** [comment]
Which version Python you are using? 
for me, it works on Python 3.4.3

**Comment by aflexa** [comment]
I am using the same version ---> Python 3.4.3

**Comment by aflexa** [comment]
it doesn't work only on Remnux (based on Ubuntu 14.04) -> current system, on all other systems it works just fine....

**Comment by secrary** [comment]
I think it's python library conflict or something like that. 
Did you try with virtualenv?
instruction is on the main page.
