### ISSUE TITLE
expand its ability

### ISSUE THREAD

**Issue by firmianay** [secrary/SSMA#7]
The project is nice, it would be more powerful if supporting ELF or APK, would you have some plans to do that?

**Comment by secrary** [comment]
It would be good, but not yet.

**Comment by firmianay** [comment]
OK, I mean if i contribute this code, are you willing to receive it? Its my first time to join a project, so i ask for some advices...

**Comment by secrary** [comment]
I've not much knowledge about malicious things in ELF or APK format, it's quite different than PE format.
If you provide some research paper or post about malicious ELF/APK, I'll try to implement it or review your code before approving it.
Thank you for contribute ^^

**Comment by firmianay** [comment]
This is the [ELF formal](www.skyfree.org/linux/references/ELF_Format.pdf). And I checkout a new branch for it.

**Comment by secrary** [comment]
That's cool. Thank you

**Comment by firmianay** [comment]
Oh, its so great! Thank you very much!
